"""Generated by scripts/generate_clients.py; OpenAPI SHA256 3cea8bc29adf3dd7ab60f48b418a77478e3e4502357e1e23de4a2f7e97088a3f."""

from __future__ import annotations

from typing import Literal, NotRequired, TypedDict

__all__ = [
    "BenchmarkDetail",
    "BenchmarkNotice",
    "BenchmarkQuoteAvailability",
    "BenchmarkRecord",
    "BillingSnapshot",
    "CatalogBenchmarksParams",
    "CatalogEnvironmentsParams",
    "CatalogEvalsParams",
    "CatalogModelsParams",
    "ComparisonModel",
    "ConnectedModel",
    "ConnectionRecord",
    "ConnectionsListParams",
    "CoverageCounts",
    "CoverageRecord",
    "EnvironmentFamily",
    "EnvironmentLimits",
    "EnvironmentRecord",
    "EnvironmentRights",
    "EvalPricing",
    "EvalRecord",
    "EvalReference",
    "EvalsListParams",
    "EventPage",
    "ExecutionOptions",
    "FullCoverage",
    "Interval",
    "JsonValue",
    "JsonValue_Output",
    "JudgeSelection",
    "LicenseNotice",
    "ManagedModel",
    "ManagedRoute",
    "MetricRecord",
    "NewConnection",
    "NewEvaluation",
    "NewQuote",
    "NewRun",
    "OKResponse",
    "Page_BenchmarkRecord_",
    "Page_ConnectionRecord_",
    "Page_EnvironmentRecord_",
    "Page_EvalRecord_",
    "Page_ManagedRoute_",
    "Page_RunRecord_",
    "ProfileCost",
    "ProfileResult",
    "ProfileSelection",
    "Profiles",
    "QuotePlan",
    "QuoteRecord",
    "ResultCosts",
    "ResultRecord",
    "ResultSummary",
    "RetentionPolicy",
    "RunEvent",
    "RunReceipt",
    "RunRecord",
    "RunRetention",
    "RunsEventsParams",
    "RunsExecutionsParams",
    "RunsExportParams",
    "RunsListParams",
    "RunsResultsParams",
    "SampleCoverage",
    "SandboxExecutionPage",
    "SandboxExecutionRecord",
    "SandboxExecutionSummary",
    "SandboxPolicyView",
    "SelectedModel",
    "Uncertainty",
    "UpdateConnection",
]


class BenchmarkDetail(TypedDict):
    slug: str
    versions: list[BenchmarkRecord]


class BenchmarkNotice(TypedDict):
    adaptation_notice: str
    evidence_sha256: str
    licenses: list[LicenseNotice]
    manifest_sha256: str
    profile_id: str


class BenchmarkQuoteAvailability(TypedDict):
    message: NotRequired[str | None]
    reason_code: NotRequired[str | None]
    status: Literal["ready_for_quote", "unavailable"]


class BenchmarkRecord(TypedDict):
    category: NotRequired[str | None]
    code_license: NotRequired[str | None]
    data_license: NotRequired[str | None]
    description: NotRequired[str | None]
    display_policy: NotRequired[str | None]
    fewshot_config: NotRequired[dict[str, JsonValue_Output] | None]
    generation_config: NotRequired[dict[str, JsonValue_Output] | None]
    id: str
    license_url: NotRequired[str | None]
    manifest_sha256: str
    metrics: NotRequired[list[str] | None]
    name: NotRequired[str | None]
    provenance: NotRequired[dict[str, JsonValue_Output] | None]
    quote_availability: NotRequired[BenchmarkQuoteAvailability | None]
    required_capabilities: NotRequired[list[str] | None]
    runner: str
    sampling_algorithm: NotRequired[str | None]
    slug: str
    source_revision: NotRequired[str | None]
    source_url: NotRequired[str | None]
    status: str
    task_count: NotRequired[int | None]
    version: str


class BillingSnapshot(TypedDict):
    as_of: str
    cap_microusd: str
    pending: bool
    reserved_microusd: str
    spend_microusd: str


class CatalogBenchmarksParams(TypedDict):
    q: NotRequired[str]
    runner: NotRequired[
        Literal["inspect", "lm-eval", "evalplus", "livecodebench", "spreadsheetbench"] | None
    ]
    capability: NotRequired[str | None]
    status: NotRequired[Literal["candidate", "active", "quarantined", "retired"] | None]
    cursor: NotRequired[str | None]
    limit: NotRequired[int]


class CatalogEnvironmentsParams(TypedDict):
    cursor: NotRequired[str | None]
    limit: NotRequired[int]


class CatalogEvalsParams(TypedDict):
    provider: NotRequired[str | None]
    kind: NotRequired[Literal["benchmark", "environment", "remote"] | None]
    protocol: NotRequired[Literal["batch", "interactive", "agentic"] | None]
    q: NotRequired[str | None]
    behavior: NotRequired[str | None]
    availability: NotRequired[str | None]
    publisher: NotRequired[str | None]
    include_private: NotRequired[bool]
    cursor: NotRequired[str | None]
    limit: NotRequired[int]


class CatalogModelsParams(TypedDict):
    q: NotRequired[str]
    provider: NotRequired[str | None]
    capability: NotRequired[str | None]
    cursor: NotRequired[str | None]
    limit: NotRequired[int]


class ComparisonModel(TypedDict):
    kind: Literal["comparison"]
    model_id: str
    models: list[SelectedModel]


class ConnectedModel(TypedDict):
    connection_id: str
    kind: Literal["connection"]


class ConnectionRecord(TypedDict):
    base_url: str
    capabilities: list[str]
    check_result: dict[str, JsonValue_Output]
    checked_at: str | None
    config: dict[str, JsonValue_Output]
    created_at: str
    disabled_at: str | None
    id: str
    model_id: str
    name: str
    protocol: Literal["openai_chat", "openai_completions"]
    revision: int


class ConnectionsListParams(TypedDict):
    cursor: NotRequired[str | None]
    limit: NotRequired[int]


class CoverageCounts(TypedDict):
    attempted: int
    cancelled: int
    errors: int
    graded: int
    planned: int
    skipped_budget: int


class CoverageRecord(TypedDict):
    mode: Literal["sample", "full"]
    sample_count: NotRequired[int | None]
    seed: NotRequired[int | None]


class EnvironmentFamily(TypedDict):
    family: str
    versions: list[EnvironmentRecord]


class EnvironmentLimits(TypedDict):
    cpu_millis: NotRequired[int]
    duration_seconds: NotRequired[int]
    max_observation_bytes: NotRequired[int]
    max_output_tokens: NotRequired[int]
    max_steps: NotRequired[int]
    memory_mib: NotRequired[int]
    network: NotRequired[Literal["blocked"]]


class EnvironmentRecord(TypedDict):
    adapter: str
    commission_basis_points: NotRequired[int]
    created_at: str
    description: str
    id: str
    limitations: list[str]
    limits: EnvironmentLimits
    manifest_sha256: str
    name: str
    package_sha256: str
    price_version: str
    quote_availability: NotRequired[BenchmarkQuoteAvailability | None]
    ref: str
    required_capabilities: list[str]
    rights: EnvironmentRights
    status: str
    supplier_fee_microusd: str
    task_counts: dict[str, int]
    validation: dict[str, JsonValue_Output]
    visibility: str


class EnvironmentRights(TypedDict):
    attribution: str
    commercial_execution: bool
    display: bool
    export: bool
    license: str
    source_url: str
    training: bool
    underlying_licenses: NotRequired[list[str]]


class EvalPricing(TypedDict):
    execution_fee_microusd: NotRequired[str | None]
    price_version: str
    task_fee_microusd: NotRequired[str | None]


class EvalRecord(TypedDict):
    availability: NotRequired[str]
    availability_reason: NotRequired[str]
    behaviors: NotRequired[list[str]]
    category: NotRequired[str]
    description: str
    detail_href: NotRequired[str | None]
    display_name: str
    execution_mode: Literal["router", "provider"]
    family: NotRequired[str]
    kind: Literal["benchmark", "environment", "remote"]
    name: str
    pricing: EvalPricing
    profile_id: str | None
    protocol: Literal["batch", "interactive", "agentic"]
    provider: str
    publisher: NotRequired[str]
    ref: str
    required_capabilities: list[str]
    runner: str
    source: NotRequired[str]
    status: str
    task_count: int | None
    version: str
    visibility: NotRequired[Literal["public", "private"]]


class EvalReference(TypedDict):
    eval: str
    provider: NotRequired[str | None]
    split: NotRequired[Literal["canonical", "train", "development", "test"] | None]


class EvalsListParams(TypedDict):
    provider: NotRequired[str | None]
    kind: NotRequired[Literal["benchmark", "environment", "remote"] | None]
    protocol: NotRequired[Literal["batch", "interactive", "agentic"] | None]
    q: NotRequired[str | None]
    behavior: NotRequired[str | None]
    availability: NotRequired[str | None]
    publisher: NotRequired[str | None]
    include_private: NotRequired[bool]
    cursor: NotRequired[str | None]
    limit: NotRequired[int]


class EventPage(TypedDict):
    data: list[RunEvent]
    has_more: bool
    next_sequence: int


class ExecutionOptions(TypedDict):
    chat_enabled: NotRequired[bool]
    max_models_per_run: int


class FullCoverage(TypedDict):
    mode: Literal["full"]


class Interval(TypedDict):
    approximate: bool
    cluster_count: NotRequired[int | None]
    confidence: float
    eligible_count: int
    gains: NotRequired[int | None]
    losses: NotRequired[int | None]
    lower: float
    method: str
    resamples: NotRequired[int | None]
    sample_count: int
    seed: NotRequired[int | None]
    strata_count: int
    target: str
    unrepresented_strata: int
    upper: float
    weights: str


type JsonValue = JsonValue_Output

type JsonValue_Output = (
    str | int | float | bool | list[JsonValue_Output] | dict[str, JsonValue_Output] | None
)


class JudgeSelection(TypedDict):
    model: SelectedModel
    protocol: dict[str, JsonValue_Output]


class LicenseNotice(TypedDict):
    attribution: str
    document_sha256: str
    identifier: str
    scope: Literal["code", "data", "tests", "assets"]
    source_revision: str
    source_url: str
    text: str


class ManagedModel(TypedDict):
    kind: Literal["managed"]
    route_id: str


class ManagedRoute(TypedDict):
    capabilities: list[str]
    display_name: str
    generation: NotRequired[dict[str, JsonValue_Output] | None]
    hosting_provider: NotRequired[str | None]
    id: str
    limits: NotRequired[dict[str, JsonValue_Output] | None]
    model_id: str
    price_version: str
    pricing: dict[str, JsonValue_Output]
    provider: str
    revision: int
    status: str


class MetricRecord(TypedDict):
    direction: Literal["higher_is_better", "lower_is_better"] | None
    key: str
    name: str
    sample_count: int | None
    source: str
    standard_error: float | None
    task: str
    uncertainty: NotRequired[Uncertainty | None]
    value: int | float


class NewConnection(TypedDict):
    api_key: str
    base_url: str
    context_window: NotRequired[int]
    max_output_tokens: NotRequired[int]
    model_id: str
    name: str
    protocol: NotRequired[Literal["openai_chat", "openai_completions"]]


class NewEvaluation(TypedDict):
    budget_usd: NotRequired[float | str | None]
    coverage: NotRequired[SampleCoverage | FullCoverage | None]
    eval: str
    max_charge_microusd: NotRequired[str | None]
    metadata: NotRequired[dict[str, str]]
    model: str | ManagedModel | ConnectedModel
    name: NotRequired[str]
    provider: NotRequired[str | None]
    split: NotRequired[str | None]


class NewQuote(TypedDict):
    selection: Profiles | EvalReference
    model: ManagedModel | ConnectedModel
    coverage: NotRequired[SampleCoverage | FullCoverage | None]
    max_charge_microusd: str


class NewRun(TypedDict):
    metadata: NotRequired[dict[str, str]]
    name: NotRequired[str]
    quote_id: str


class OKResponse(TypedDict):
    ok: bool


class Page_BenchmarkRecord_(TypedDict):
    data: list[BenchmarkRecord]
    next_cursor: str | None


class Page_ConnectionRecord_(TypedDict):
    data: list[ConnectionRecord]
    next_cursor: str | None


class Page_EnvironmentRecord_(TypedDict):
    data: list[EnvironmentRecord]
    next_cursor: str | None


class Page_EvalRecord_(TypedDict):
    data: list[EvalRecord]
    next_cursor: str | None


class Page_ManagedRoute_(TypedDict):
    data: list[ManagedRoute]
    next_cursor: str | None


class Page_RunRecord_(TypedDict):
    data: list[RunRecord]
    next_cursor: str | None


class ProfileCost(TypedDict):
    charged_microusd: str
    model_index: NotRequired[int | None]
    pending_operations: int
    profile_id: str
    total_cost_microusd: str | None


class ProfileResult(TypedDict):
    cancelled: int
    data_license: str | None
    display_policy: NotRequired[str | None]
    eligible: int | None
    error_code: str | None
    errors: int
    graded: int
    headline_key: str | None
    license_url: str | None
    metrics: list[MetricRecord]
    model_index: NotRequired[int | None]
    name: str
    native: dict[str, JsonValue_Output] | None
    planned: int
    profile_id: str
    runner: str
    selection: ProfileSelection
    skipped_budget: int
    source_revision: str | None
    source_url: str | None
    status: str
    uncertainty: NotRequired[dict[str, Uncertainty] | None]
    uncertainty_note: str
    unit_id: str


class ProfileSelection(TypedDict):
    admission: NotRequired[dict[str, JsonValue_Output] | None]
    attempts_per_task: NotRequired[int]
    dataset_assets_sha256: str
    environment: NotRequired[dict[str, JsonValue_Output] | None]
    id: str
    judge: NotRequired[JudgeSelection | None]
    manifest_sha256: str
    population_count: int
    private_test: NotRequired[bool | None]
    remote: NotRequired[dict[str, JsonValue_Output] | None]
    sampling_algorithm: str
    sandbox: NotRequired[SandboxPolicyView | None]
    selected_count: int
    task_ids: NotRequired[list[str] | None]
    task_ids_hash: str


class Profiles(TypedDict):
    profile_ids: list[str]


class QuotePlan(TypedDict):
    agent: NotRequired[dict[str, JsonValue_Output] | None]
    agents: NotRequired[list[dict[str, JsonValue_Output]] | None]
    coverage: CoverageRecord
    model: SelectedModel | ComparisonModel
    pricing: dict[str, JsonValue_Output]
    profiles: list[ProfileSelection]
    recommendation: NotRequired[dict[str, JsonValue_Output] | None]
    route: NotRequired[dict[str, JsonValue_Output] | None]
    schema_version: Literal[1, 2, 3, 4]
    selection_source: dict[str, JsonValue_Output]
    total_tasks: int
    warnings: list[str]


class QuoteRecord(TypedDict):
    created_at: str
    estimated_charge_microusd: str
    expires_at: str
    id: str
    max_charge_microusd: str
    plan: QuotePlan
    price_version: str
    retention: RetentionPolicy


class ResultCosts(TypedDict):
    as_of: str
    basis: Literal["managed_total", "platform_fees_only", "mixed"]
    currency: Literal["USD"]
    note: str
    profiles: list[ProfileCost]


class ResultRecord(TypedDict):
    benchmark_notices: list[BenchmarkNotice]
    checksum: str
    costs: ResultCosts
    coverage: CoverageRecord | None
    envelope: NotRequired[dict[str, JsonValue_Output] | None]
    finalized_at: str
    id: str
    manifest_hash: str
    model: SelectedModel | ComparisonModel
    profiles: list[ProfileResult]
    retention: RunRetention
    run_id: str
    summary: ResultSummary
    version: int


class ResultSummary(TypedDict):
    billing_snapshot: BillingSnapshot
    coverage: CoverageCounts
    finished_at: str
    manifest_hash: str
    name: str
    result_version: int
    run_id: str
    schema_version: Literal[1]
    status: Literal["completed", "partial", "failed", "cancelled"]
    terminal_reason: str | None


class RetentionPolicy(TypedDict):
    raw_days: int
    starts_at: Literal["run_created_at"]
    summary_days: int


class RunEvent(TypedDict):
    created_at: str
    data: dict[str, JsonValue_Output]
    sequence: int
    type: str


class RunReceipt(TypedDict):
    billing_state: Literal["pending", "settled", "reconciliation_required"]
    cap_microusd: str
    created_at: str
    currency: Literal["USD"]
    report_expired: bool
    reserved_microusd: str
    run_id: str
    spend_microusd: str
    summary_expires_at: str


class RunRecord(TypedDict):
    agent: NotRequired[dict[str, JsonValue_Output] | None]
    agents: NotRequired[list[dict[str, JsonValue_Output]] | None]
    billing_state: Literal["pending", "settled", "reconciliation_required"]
    cancel_requested_at: str | None
    cap_microusd: str
    completed_count: int
    coverage: CoverageRecord | None
    created_at: str
    error_count: int
    finished_at: str | None
    id: str
    manifest_hash: str
    metadata: dict[str, str]
    model: SelectedModel | ComparisonModel
    name: str
    planned_count: int
    profiles: list[ProfileSelection]
    reserved_microusd: str
    retention: RunRetention
    retry_at: NotRequired[str | None]
    route: NotRequired[dict[str, JsonValue_Output] | None]
    spend_microusd: str
    started_at: str | None
    status: Literal[
        "queued",
        "running",
        "cancelling",
        "finalizing",
        "completed",
        "partial",
        "failed",
        "cancelled",
    ]
    terminal_reason: str | None
    waiting_reason: NotRequired[str | None]


class RunRetention(TypedDict):
    raw_evidence_expired: bool
    raw_expires_at: str
    summary_expires_at: str


class RunsEventsParams(TypedDict):
    after: NotRequired[int]
    limit: NotRequired[int]
    tail: NotRequired[bool]


class RunsExecutionsParams(TypedDict):
    sample_id: NotRequired[str | None]
    cursor: NotRequired[str | None]
    limit: NotRequired[int]


class RunsExportParams(TypedDict):
    format: NotRequired[Literal["json", "csv", "html"]]
    version: NotRequired[int | None]


class RunsListParams(TypedDict):
    cursor: NotRequired[str | None]
    limit: NotRequired[int]


class RunsResultsParams(TypedDict):
    version: NotRequired[int | None]


class SampleCoverage(TypedDict):
    mode: NotRequired[Literal["sample"]]
    sample_count: NotRequired[int]
    seed: NotRequired[int]


class SandboxExecutionPage(TypedDict):
    data: list[SandboxExecutionRecord]
    next_cursor: str | None
    summary: SandboxExecutionSummary


class SandboxExecutionRecord(TypedDict):
    attempt_no: int
    cleanup_status: Literal["not_requested", "pending", "stopped"]
    cpu_millis: int
    created_at: str
    error_code: str | None
    execution_started_at: str | None
    id: str
    memory_mib: int
    model_index: int
    profile_id: str
    sample_id: str
    status: Literal["intent", "creating", "ready", "executing", "finished", "stopping", "stopped"]
    stopped_at: str | None
    task_id: str
    timeout_seconds: int
    verifier_result_recorded: bool


class SandboxExecutionSummary(TypedDict):
    active_count: int
    allocated_count: int
    cleanup_pending_count: int
    stopped_count: int


class SandboxPolicyView(TypedDict):
    backend: NotRequired[str]
    cpu_millis: NotRequired[int]
    execution_class: NotRequired[str]
    execution_fee_microusd: str
    image_id: str
    image_sha256: str
    max_infrastructure_attempts: NotRequired[int]
    memory_mib: NotRequired[int]
    network: NotRequired[str]
    price_version: str
    schema_version: NotRequired[Literal[1]]
    timeout_seconds: NotRequired[int]


class SelectedModel(TypedDict):
    artifact_id: NotRequired[str | None]
    artifact_sha256: NotRequired[str | None]
    capabilities: list[str]
    connection_id: NotRequired[str | None]
    generation: NotRequired[dict[str, JsonValue_Output] | None]
    kind: str
    likelihood: NotRequired[dict[str, JsonValue_Output] | None]
    limits: dict[str, JsonValue_Output]
    model_id: str
    price_version: NotRequired[str | None]
    pricing: NotRequired[dict[str, JsonValue_Output] | None]
    protocol: str
    provider_charges: NotRequired[str | None]
    revision: int
    route_id: NotRequired[str | None]
    routing: NotRequired[dict[str, JsonValue_Output] | None]


class Uncertainty(TypedDict):
    interval: Interval | None
    reason: str | None


class UpdateConnection(TypedDict):
    api_key: NotRequired[str | None]
    context_window: NotRequired[int | None]
    max_output_tokens: NotRequired[int | None]
    name: NotRequired[str | None]
